### ISSUE TITLE
Comments don't show up

### ISSUE THREAD

**Issue by pcuci** [coopermaruyama/meteor-side-comments#1]
Hi Cooper - I've tried your package, but comments don't show up

I'm publishing the Meteor.user().username field and it seems it's being picked up, but I don't know how it's supposed to work.

Do you have a live demo somewhere I can debug against?

**Comment by czxtm** [comment]
Ah, I forgot to import the actual JS/CSS libraries for side comments. I fixed it and also made a demo here:

demo: http://sidecomments-demo.meteor.com/
repo: https://github.com/coopermaruyama/meteor-sidecomments-demo

please let me know whether or not it works for you now.
