### ISSUE TITLE
facebook picture retrieval fails

### ISSUE THREAD

**Issue by cellog** [coopermaruyama/meteor-side-comments#4]
avatar = "//graph.facebook.com/#{fb.id}/picture" if _fb.id?

you use {fb.id} instead of {_fb.id}

Might be good to test before release, can't believe no one reported this before...

**Comment by czxtm** [comment]
Thanks for reporting. Fixed in https://github.com/coopermaruyama/meteor-side-comments/commit/2f8dcf3eb254daa3abe1bd8f907a9b71bb5e3caa

**Comment by cellog** [comment]
thanks! very fast.

**Comment by cellog** [comment]
how long do you think before the push will appear through meteor update?

**Comment by czxtm** [comment]
done

**Comment by czxtm** [comment]
can you do me a favor just post a comment here when you've confirmed it's working ok?

**Comment by cellog** [comment]
confimed working

**Comment by czxtm** [comment]
sweet! thanks
